name: |
    [DEV] Docker Build & Publish

concurrency:
    group: chuck-app
    cancel-in-progress: true

on:
    workflow_dispatch:
    push:
        branches:
            - main

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: daguitosama/chuck-app
    TURBO_TELEMETRY_DISABLED: 1
    NODE_OPTIONS: --max-old-space-size=8192

jobs:
    build-api-x64:
        name: Build & Publish Docker Image
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            # - id: setup-qemu
            #   name: Set up QEMU
            #   uses: docker/setup-qemu-action@v3

            # - id: set-up-buildx
            #   name: Set up Docker Buildx
            #   uses: docker/setup-buildx-action@v3

            - name: Login Into GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - id: metadata
              name: Extract metadata (labels) for Docker
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: Dockerfile
                  push: true
                  # platforms: linux/amd64,linux/arm64
                  tags: |
                      ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev
                      ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev-${{ github.sha }}
                  labels: ${{ steps.metadata.outputs.labels }}
